### ISSUE TITLE
Dio() not included?

### ISSUE THREAD

**Issue by shero1111** [salomaosnff/oauth_dio#15]
Hello,

It seems that Dio() ist not available, even after import...

`import 'package:oauth_dio/oauth_dio.dart';
`
`    final authenticadedDio = Dio();
    authenticadedDio.interceptors.add(BearerInterceptor(oauth));
`

in pubspec.yaml dependencies:

`  oauth_dio: ^0.2.7
`

**Comment by salomaosnff** [comment]
> Hello,
> 
> It seems that Dio() ist not available, even after import...
> 
> `import 'package:oauth_dio/oauth_dio.dart'; ` ` final authenticadedDio = Dio(); authenticadedDio.interceptors.add(BearerInterceptor(oauth));`
> 
> in pubspec.yaml dependencies:
> 
> ` oauth_dio: ^0.2.7`

Dio must be installed separately.
