### ISSUE TITLE
Pb using FlutterSecureStorage

### ISSUE THREAD

**Issue by fvisticot** [salomaosnff/oauth_dio#7]
Exemple provided with the application using FlutterSecureStorage seems not correct.
- The "Save" method of the SecureStorage does not take the expiration into account.
- OAuthToken does not have constructor with params

**Comment by salomaosnff** [comment]
@fvisticot
You can return:
```dart
OAuthToken.fromMap ({
   "access_token": "<AccessToken>",
   "refresh_token": "<RefreshToken>",
   "expires": "<Seconds>" // a integer
})
```

**Comment by fvisticot** [comment]
> @fvisticot
> You can return:
> 
> ```dart
> OAuthToken.fromMap ({
>    "access_token": "<AccessToken>",
>    "refresh_token": "<RefreshToken>",
>    "expires": "<Seconds>" // a integer
> })
> ```

I have the following implementation for the securestorage.
- I need to compute the "expires" token property from "now"
- I need to save the expiration date in the secure storage

Do you think that this implementation is correct ? (expires field management ?)

Other question: 
- What is happening when you request a new token from refreshToken and get an error from server (by exemple refreshToken expired) ?
In my case the refreshToken expiration is 30 days... What is hapenning in your implementation in that case ?
- I see in your code that the toMap token export provide a expires value in ms. is it normal ? should be in second ?

 ```dart
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:oauth_dio/oauth_dio.dart';

class OAuthSecureStorage extends OAuthStorage {
  final FlutterSecureStorage storage = FlutterSecureStorage();
  final accessTokenKey = 'accessToken';
  final refreshTokenKey = 'refreshToken';
  final expirationKey = 'expiration';

  @override
  Future<OAuthToken> fetch() async {
    final accessToken = await storage.read(key: accessTokenKey);
    final refreshToken = await storage.read(key: refreshTokenKey);
    final String expiration = await storage.read(key: expirationKey);

    if (accessToken != null && refreshToken != null && expiration != null) {
      final expirationDate = DateTime.parse(expiration);
      final now = DateTime.now();
      final int expires = ((expirationDate.millisecondsSinceEpoch -
              now.millisecondsSinceEpoch) ~/
          1000);
      return OAuthToken.fromMap({
        'access_token': accessToken,
        'refresh_token': refreshToken,
        'expires': expires
      });
    } else {
      return null;
    }
  }

  @override
  Future<OAuthToken> save(OAuthToken token) async {
    await storage.write(key: accessTokenKey, value: token.accessToken);
    await storage.write(key: refreshTokenKey, value: token.refreshToken);
    await storage.write(
        key: expirationKey, value: token.expiration.toIso8601String());
    return token;
  }

  Future<void> clear() async {
    await storage.delete(key: accessTokenKey);
    await storage.delete(key: refreshTokenKey);
    await storage.delete(key: expirationKey);
  }
}

```

**Comment by salomaosnff** [comment]
> > @fvisticot
> > You can return:
> > ```dart
> > OAuthToken.fromMap ({
> >    "access_token": "<AccessToken>",
> >    "refresh_token": "<RefreshToken>",
> >    "expires": "<Seconds>" // a integer
> > })
> > ```
> 
> I have the following implementation for the securestorage.
> 
> * I need to compute the "expires" token property from "now"
> * I need to save the expiration date in the secure storage
> 
> Do you think that this implementation is correct ? (expires field management ?)
> 
> Other question:
> 
> * What is happening when you request a new token from refreshToken and get an error from server (by exemple refreshToken expired) ?
>   In my case the refreshToken expiration is 30 days... What is hapenning in your implementation in that case ?
> * I see in your code that the toMap token export provide a expires value in ms. is it normal ? should be in second ?
> 
> ```dart
> import 'package:flutter_secure_storage/flutter_secure_storage.dart';
> import 'package:oauth_dio/oauth_dio.dart';
> 
> class OAuthSecureStorage extends OAuthStorage {
>  final FlutterSecureStorage storage = FlutterSecureStorage();
>  final accessTokenKey = 'accessToken';
>  final refreshTokenKey = 'refreshToken';
>  final expirationKey = 'expiration';
> 
>  @override
>  Future<OAuthToken> fetch() async {
>    final accessToken = await storage.read(key: accessTokenKey);
>    final refreshToken = await storage.read(key: refreshTokenKey);
>    final String expiration = await storage.read(key: expirationKey);
> 
>    if (accessToken != null && refreshToken != null && expiration != null) {
>      final expirationDate = DateTime.parse(expiration);
>      final now = DateTime.now();
>      final int expires = ((expirationDate.millisecondsSinceEpoch -
>              now.millisecondsSinceEpoch) ~/
>          1000);
>      return OAuthToken.fromMap({
>        'access_token': accessToken,
>        'refresh_token': refreshToken,
>        'expires': expires
>      });
>    } else {
>      return null;
>    }
>  }
> 
>  @override
>  Future<OAuthToken> save(OAuthToken token) async {
>    await storage.write(key: accessTokenKey, value: token.accessToken);
>    await storage.write(key: refreshTokenKey, value: token.refreshToken);
>    await storage.write(
>        key: expirationKey, value: token.expiration.toIso8601String());
>    return token;
>  }
> 
>  Future<void> clear() async {
>    await storage.delete(key: accessTokenKey);
>    await storage.delete(key: refreshTokenKey);
>    await storage.delete(key: expirationKey);
>  }
> }
> ```

According to the OAuth 2.0 specification, it is recommended that your authentication server return an "expires_in" field containing the token lifetime in seconds.

See https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2

The expires field will also prevent sending invalid tokens to the server, validating the tokens before sending them in the request.

**Comment by fvisticot** [comment]
> > > @fvisticot
> > > You can return:
> > > ```dart
> > > OAuthToken.fromMap ({
> > >    "access_token": "<AccessToken>",
> > >    "refresh_token": "<RefreshToken>",
> > >    "expires": "<Seconds>" // a integer
> > > })
> > > ```
> > 
> > 
> > I have the following implementation for the securestorage.
> > 
> > * I need to compute the "expires" token property from "now"
> > * I need to save the expiration date in the secure storage
> > 
> > Do you think that this implementation is correct ? (expires field management ?)
> > Other question:
> > 
> > * What is happening when you request a new token from refreshToken and get an error from server (by exemple refreshToken expired) ?
> >   In my case the refreshToken expiration is 30 days... What is hapenning in your implementation in that case ?
> > * I see in your code that the toMap token export provide a expires value in ms. is it normal ? should be in second ?
> > 
> > ```dart
> > import 'package:flutter_secure_storage/flutter_secure_storage.dart';
> > import 'package:oauth_dio/oauth_dio.dart';
> > 
> > class OAuthSecureStorage extends OAuthStorage {
> >  final FlutterSecureStorage storage = FlutterSecureStorage();
> >  final accessTokenKey = 'accessToken';
> >  final refreshTokenKey = 'refreshToken';
> >  final expirationKey = 'expiration';
> > 
> >  @override
> >  Future<OAuthToken> fetch() async {
> >    final accessToken = await storage.read(key: accessTokenKey);
> >    final refreshToken = await storage.read(key: refreshTokenKey);
> >    final String expiration = await storage.read(key: expirationKey);
> > 
> >    if (accessToken != null && refreshToken != null && expiration != null) {
> >      final expirationDate = DateTime.parse(expiration);
> >      final now = DateTime.now();
> >      final int expires = ((expirationDate.millisecondsSinceEpoch -
> >              now.millisecondsSinceEpoch) ~/
> >          1000);
> >      return OAuthToken.fromMap({
> >        'access_token': accessToken,
> >        'refresh_token': refreshToken,
> >        'expires': expires
> >      });
> >    } else {
> >      return null;
> >    }
> >  }
> > 
> >  @override
> >  Future<OAuthToken> save(OAuthToken token) async {
> >    await storage.write(key: accessTokenKey, value: token.accessToken);
> >    await storage.write(key: refreshTokenKey, value: token.refreshToken);
> >    await storage.write(
> >        key: expirationKey, value: token.expiration.toIso8601String());
> >    return token;
> >  }
> > 
> >  Future<void> clear() async {
> >    await storage.delete(key: accessTokenKey);
> >    await storage.delete(key: refreshTokenKey);
> >    await storage.delete(key: expirationKey);
> >  }
> > }
> > ```
> 
> According to the OAuth 2.0 specification, it is recommended that your authentication server return an "expires_in" field containing the token lifetime in seconds.
> 
> See https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2
> 
> The expires field will also prevent sending invalid tokens to the server, validating the tokens before sending them in the request.

Tx for the reply.
I check your code and it seems that in case the server returns an error on the refreshToken POST call, the error is not fired and the application stays blocked
